// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyZPvTBojBDbNFSaArL41i4bCk2kiUlx4',
    appId: '1:658440818209:web:52f6d30290a82548c0dd60',
    messagingSenderId: '658440818209',
    projectId: 'anydeck-64159',
    authDomain: 'anydeck-64159.firebaseapp.com',
    storageBucket: 'anydeck-64159.appspot.com',
    measurementId: 'G-R625DHRRH7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6GIcJLk5DSyRPZXQPo08XdReAgtEeOX8',
    appId: '1:658440818209:android:bc410c3ed61c3b5ac0dd60',
    messagingSenderId: '658440818209',
    projectId: 'anydeck-64159',
    storageBucket: 'anydeck-64159.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-tt23OwLpfvPdCbw4PdnbatZuWCvhrfo',
    appId: '1:658440818209:ios:1b868f27c0c6ffeec0dd60',
    messagingSenderId: '658440818209',
    projectId: 'anydeck-64159',
    storageBucket: 'anydeck-64159.appspot.com',
    iosBundleId: 'com.example.flutterInterview',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-tt23OwLpfvPdCbw4PdnbatZuWCvhrfo',
    appId: '1:658440818209:ios:1b868f27c0c6ffeec0dd60',
    messagingSenderId: '658440818209',
    projectId: 'anydeck-64159',
    storageBucket: 'anydeck-64159.appspot.com',
    iosBundleId: 'com.example.flutterInterview',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyZPvTBojBDbNFSaArL41i4bCk2kiUlx4',
    appId: '1:658440818209:web:4b8a02eda7b8df72c0dd60',
    messagingSenderId: '658440818209',
    projectId: 'anydeck-64159',
    authDomain: 'anydeck-64159.firebaseapp.com',
    storageBucket: 'anydeck-64159.appspot.com',
    measurementId: 'G-E9WY3W023M',
  );
}
